# -*- coding: utf-8 -*-
"""decision_tree_MNIST_student_code_0510.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KlmmzLMWmrZUtTVlL2M-JYScR707VRRN

### student code
## STEP1. Load MNIST data and split into train and test data
"""

import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print('... loading data')
with open('mnist.pkl', 'rb') as f:
     train_set, valid_set, test_set = pickle.load(f, encoding='latin1')
# with open('/content/drive/MyDrive/교과목개발/data/mnist.pkl', 'rb') as f:
#     train_set, valid_set, test_set = pickle.load(f, encoding='latin1')

train_x, train_y = train_set
test_x, test_y = test_set

train_x = pd.DataFrame(train_x)
train_y = pd.DataFrame(train_y, columns=['label'])
test_x = pd.DataFrame(test_x)
test_y = pd.DataFrame(test_y, columns=['label'])

sub_train_x = train_x.iloc[:500, :]
sub_train_y = train_y.iloc[:500]
sub_test_x = test_x.iloc[:100, :]
sub_test_y = test_y.iloc[:100, :]

"""----
## STEP2 Classify MNIST data using __Decision Tree__🌲 sklearn library 
"""

from sklearn.tree import DecisionTreeClassifier

decisionTree = DecisionTreeClassifier(random_state=0, criterion='entropy')
decisionTree.fit(train_x, train_y)

print("=== > Test set score : {:.2f}".format(decisionTree.score(test_x, test_y)))

"""---
## STEP3 Classify MNIST data using __Random Forest__🌲 sklearn library 
"""

from sklearn.ensemble import RandomForestClassifier

rforest = RandomForestClassifier(random_state=0)
rforest.fit(train_x, train_y.values.ravel())

print("Test set score : {:.2f}".format(rforest.score(test_x, test_y)))

"""-----
## STEP4 Visualization of result
"""

from sklearn.metrics import confusion_matrix
import seaborn as sn

pred_y = decisionTree.predict(test_x)
cmdtree = confusion_matrix(test_y, pred_y)

plt.figure(figsize=(10,7))
sn.heatmap(cmdtree, annot=True, fmt='d')

plt.title(" < CONFUSION MATRIX > ")
plt.ylabel('Predicted label')
plt.xlabel('True Label')

# plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sn

## YOUR CODE STARTS HERE
pred_y = rforest.predict(test_x)
rtree_cmd = confusion_matrix(test_y, pred_y)

plt.figure(figsize = (10, 7))
sn.heatmap(rtree_cmd, annot=True, fmt='d')

plt.title(" < CONFUSION MATRIX > ")
plt.ylabel('Predicted label')
plt.xlabel('True Label')

plt.show()