# -*- coding: utf-8 -*-
"""Week10_Practice.ipynb_for_student.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bI17DDxoCRLhKmMLCMusZcT_bnZ4FS3L

# 1️⃣ Simple Linear Regression
## What is Regression?
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

#Our model forward pass
def forward(x):
    return x * w

# Loss function
def loss(y_pred, y):
    return (y_pred - y) * (y_pred - y)

w = 0.00  # initial w
for epoch in range(30):
    for x, y in zip(x_data, y_data):
        y_pred = forward(x)
        l = loss(y_pred, y)
        if x == 3:
            print("Epoch", epoch, "\t(x,y): ", x, y, "\tw=", "%.2f"%w, "\tloss=", "%.2f"%l)
        w = w + 0.05
    plt.scatter(w, l, color = 'r')

# Training Data
x_data = [1, 2, 3]
y_data = [2, 4, 6]

# compute gradient
def gradient(x, y):  # d_loss/d_w
    return 2 * x * (x * w - y)

w = 1.00  # initial w
for epoch in range(30):
    for x, y in zip(x_data, y_data):
        y_pred = forward(x)
        l = loss(y_pred, y)
        grad = gradient(x, y)
        if x == 3:
            print("Epoch", epoch, "\t(x,y): ", x, y,
                  "\tw=", "%.2f" % w, "\tloss=", "%.2f" % l, "\tGrad=", "%.2f" % grad)
        w = w - 0.005 * grad
    plt.scatter(w, l, color='r')

# After training
print("Predicted score (after training)",  "When x=4, y will be : ", forward(4))
print("Predicted score (after training)",  "When x=4, y will be : ", forward(6))

"""# Exercise1: speed of sound"""

x_data = [0.0, 1.0, 2.0, 3.0]
y_data = [331.0, 331.6, 332.2, 332.8]
w=0.0
b=0.0

epochs = 1000
learning_rate = 0.03
for i in range(epochs):
    for x, y in zip(x_data, y_data):
        y_pred = x * w + b
        loss = ((y_pred - y) ** 2) # MSE
        grad_w = ((w * x + b - y) * 2 * x)
        grad_b = ((w * x + b - y) * 2)
        w -= learning_rate * grad_w
        b -= learning_rate * grad_b

x_new = 20
y_pred = x_new * w + b
print(y_pred)

"""# 1️⃣ Linear Regression Using Real Estate Data
## sklearn Regression
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_excel('data_set_train.xlsx')
df.head()

df.corr().head()

df_2017q1 = df[df['yyyyqrt(거래년도 분기별)'] == '2017Q1']
df_2017q1.corr().head(5)

# Area vs. Price
plt.figure(figsize=(12, 5))
plt.scatter(df_2017q1['area(면적)'], df_2017q1['price(가격)'], alpha=0.1)
plt.xlabel('area')
plt.ylabel('price')
# plt.show()

from sklearn.model_selection import train_test_split

#Split data into training set and test set
x = np.array(df_2017q1['area(면적)']).reshape(-1, 1)
y = np.array(df_2017q1['price(가격)']).reshape(-1, 1)
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.10, random_state=2)

print("train_x shape  = ",train_x.shape, "train_y shape  = ", train_y.shape)
print("test_x shape  = ",test_x.shape, "test_y shape  = ", test_y.shape)

# Training
simple_lin_reg = LinearRegression(normalize=True)
simple_lin_reg.fit(train_x, train_y)
print("Fitting results: ", 'w = ', simple_lin_reg.intercept_, 'b = ', simple_lin_reg.coef_ )

# Prediction
test_y_pred = simple_lin_reg.predict(test_x)
print("Testing results: ", 'score = ', simple_lin_reg.score(test_x, test_y))

# Visulization
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.scatter(train_x,train_y,color='k')
plt.scatter(train_x,simple_lin_reg.predict(train_x),color='c')
plt.title('Training data'); plt.xlim(0, 260)
plt.ylim(0, 550000)

plt.subplot(1, 2, 2)
plt.scatter(test_x, test_y, color ='k')
plt.scatter(test_x, test_y_pred,color='r')
plt.title('Testing data'); plt.xlim(0, 260)
plt.ylim(0, 550000)

"""# Regression by Quadratic function"""

# Generating X^2
train_x_s = np.c_[train_x, train_x**2]
test_x_s = np.c_[test_x, test_x**2]

train_x_s

# Training
lin_reg_poly = LinearRegression(normalize=True)
lin_reg_poly.fit(train_x_s, train_y)
print("Fitting results: ", 'b = ', lin_reg_poly.intercept_, 'w = ', lin_reg_poly.coef_)

# Prediction
test_y_pred_poly = lin_reg_poly.predict(test_x_s)
print("Testing results: ", 'score = ', lin_reg_poly.score(test_x_s, test_y))

# Visualization
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.scatter(test_x, test_y, color ='k')
plt.scatter(test_x, test_y_pred,color='r')
plt.title('Testing data - Linear')
plt.xlim(0, 260); plt.ylim(0, 550000)

plt.subplot(1, 2, 2)
plt.scatter(test_x[:,0], test_y, color ='k')
plt.scatter(test_x[:,0], test_y_pred_poly, color ='b')
plt.title('Testing data - Polynomial'); plt.xlim(0, 260)
plt.ylim(0, 550000)

"""## Multiple Regression"""

# for 2017q1
df_2017q1 = df[df['yyyyqrt(거래년도 분기별)'] == '2017Q1']

df_2017q1

df_2017q1_mf = df_2017q1.copy()
col = df_2017q1.columns
for c in col:
    if df_2017q1_mf[c].dtypes == 'object':
        df_2017q1_mf = df_2017q1_mf.drop(c, axis=1)
        continue
    # 강의자료에 있는 코드랑 조금 다른 부분
    if df_2017q1_mf[c].var() == 0:
        df_2017q1_mf = df_2017q1_mf.drop(c, axis=1)
df_2017q1_mf['Yongpae(용적률)'] = df_2017q1_mf['Yongpae(용적률)'].replace(np.nan, df_2017q1_mf['Yongpae(용적률)'].mean())
df_2017q1_mf['Gunpae(건폐율)'] = df_2017q1_mf['Gunpae(건폐율)'].replace(np.nan, df_2017q1_mf['Gunpae(건폐율)'].mean())
df_2017q1_mf

x_train, x_test, y_train, y_test = train_test_split(df_2017q1_mf.iloc[:, 1:], df_2017q1_mf.iloc[:, 0], test_size=0.10, random_state=2)


print("X_train.shape =", x_train.shape)
print("y_train.shape =", y_train.shape)

print("X_test.shape =", x_test.shape)
print("y_test.shape =", y_test.shape)

# create object 
mul_reg = LinearRegression(normalize=True)
# train
mul_reg.fit(x_train, y_train)

# check coefficients and intercept
print("coef_:", mul_reg.coef_)             # w
print("intercept_:", mul_reg.intercept_)   # b

# evaluation
print("Training set score: {:.2f}".format(mul_reg.score(x_train, y_train)))
print("Test set score: {:.2f}".format(mul_reg.score(x_test, y_test)))

"""## Lasso ($L_1$ regularization)"""

from sklearn.linear_model import Lasso

print("x_train.shape =", x_train.shape)
print("y_train.shape =", y_train.shape)
print("x_test.shape =", x_test.shape)
print("y_test.shape =", y_test.shape)

lasso = Lasso(alpha=1, normalize=True).fit(x_train, y_train)
print("Training score: {:.2f}".format(lasso.score(x_train, y_train)))
print("Test score: {:.2f}".format(lasso.score(x_test, y_test)))
print("Number of features used:", np.sum(lasso.coef_ != 0))

lasso001 = Lasso(0.01, normalize=True).fit(x_train, y_train)
print("Training score: {:.2f}".format(lasso.score(x_train, y_train)))
print("Test score: {:.2f}".format(lasso.score(x_test, y_test)))
print("Number of features used:", np.sum(lasso.coef_ != 0))

"""## Ridge ($L_2$ regularization)"""

from sklearn.linear_model import Ridge

ridge = Ridge(alpha=0.01, normalize=True).fit(x_train, y_train)
print("ridge.coef_: {}".format(ridge.coef_))             # w
print("ridge.intercept_: {}".format(ridge.intercept_))   # b

print("Training score: {:.2f}".format(ridge.score(x_train, y_train)))
print("Test score: {:.2f}".format(ridge.score(x_test, y_test)))

"""# Multiple regression with whole data - not included in ppt"""

#   multiple regression for whole data

df_multi = df.copy()
col = df.columns
for c in col:
    #print(df[c].dtypes)
    if(df_multi[c].dtypes == 'object'):
        df_multi=df_multi.drop(c,axis=1)
        continue
#columns=df_multi.columns
#for c in columns:
    #print(df_2017q1_1f[c].dtypes)
df_multi['Yongpae(용적률)']=df_multi['Yongpae(용적률)'].replace(np.nan,df_multi['Yongpae(용적률)'].mean())
df_multi['Gunpae(건폐율)']=df_multi['Gunpae(건폐율)'].replace(np.nan,df_multi['Gunpae(건폐율)'].mean())
df_multi

X_train, X_test, y_train, y_test = train_test_split( df_multi.iloc[:,1:], df_multi.iloc[:,0],test_size = 0.3, random_state=0)
print("x_train.shape =", x_train.shape)
print("y_train.shape =", y_train.shape)
print("x_test.shape =", x_test.shape)
print("y_test.shape =", y_test.shape)

# create object 
lr = LinearRegression(normalize=True)

# train
lr.fit(X_train, y_train)

# the above two statements can be combined as the next line
# lr = LinearRegression().fit(X_train, y_train)

# check coefficients and intercept
print("lr.coef_:", lr.coef_)             # w
print("lr.intercept_:", lr.intercept_)   # b

# evaluation
print("Training set score: {:.2f}".format(lr.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lr.score(X_test, y_test)))

plt.show() # for all contents printing